import {liveMapView,mapHeaderActions} from './live-map.mjs?v=notes3';
import {sceneList,stamp} from './handoff.mjs?v=handoff3';
import {streetMap} from './map-scene.mjs?v=ops1';
import {sources,sourceById} from './media.mjs?v=theme-scene2';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const timecode=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
export function mapView(s,ic,select,side){return liveMapView(s,ic,select,side);}
export function videoView(s,ic){
 const source=sourceById(s.camera,s.theme),ar=source.id==='ar';
 const records=s.records.filter(r=>r.source===source.id).slice(0,3);
 return `<div class="row"><div class="eyebrow">${ar?'나의 시야와 현장을 연결합니다':'현장에 연결된 영상'}</div><span class="tag subtle">샘플 재생</span></div><h2 class="tool-heading">${source.name}</h2><p class="subcopy">${source.place} · 촬영 ${source.time}</p>
 <div class="video-context"><span>영상 ${stamp(source.duration)}</span><p>${source.summary}</p><small>확인할 지점 · ${source.check}</small></div>${sceneList(s)}
 ${ar?`<button class="ar-device-strip" data-action="nav" data-view="device"><img src="assets/parallax-glasses.png" alt="사용자 제공 PARALLAX AR 글래스"><span><strong>PARALLAX Glass</strong><small><i class="dot"></i>${s.connected?'연결됨':'연결 끊김'} · 82%</small></span>${ic('chevron')}</button>`:''}
 <div class="video-frame ${ar?'ar-viewport':''}" data-frame><img class="scene-image" src="assets/${source.image}" alt="${ar?'AR 글래스 시점의 가상 2층 계단실':source.id==='drone'?'가상 현장 드론 시점':'가상 공동현관 CCTV 시점'}"><div class="video-overlay"><span class="media-badge">${ic(source.icon)}${ar?'내 시야':source.name} · 예시</span><span class="media-time">${source.time}</span></div>
 ${ar&&s.hud?`<div class="ar-reticle" aria-hidden="true"><i></i><i></i><i></i><i></i></div><button class="ar-anchor" data-action="ar-marker">${ic('pin')}2층 계단실 <span>현장 기록 1건</span></button><div class="ar-heading"><span>서편 확인</span><span>${ic('north')} 028°</span></div>`:''}
 <div class="video-bottom"><button class="icon-button" data-action="play" data-play aria-label="${s.playing?'샘플 일시정지':'샘플 재생'}">${ic(s.playing?'pause':'play')}</button><input class="media-seek" data-seek type="range" min="0" max="${source.duration}" value="${s.playhead}" aria-label="영상 재생 위치"><span data-play-time>${timecode(s.playhead)} / ${timecode(source.duration)}</span></div></div>
 <div class="video-tools">${ar?`<button data-action="hud" class="tool-pill ${s.hud?'active':''}" aria-pressed="${s.hud}">${ic('layers')}AR 정보 ${s.hud?'켜짐':'꺼짐'}</button>`:'<span class="muted">생성 이미지 기반 재생 시뮬레이션</span>'}<button class="tool-pill" data-action="show-location">${ic('pin')}위치 보기</button></div>
 <div class="button-row"><button class="secondary-button" data-action="bookmark-current">${ic('bookmark')}북마크</button><button class="primary-button" data-action="capture">${ic('camera')}장면 캡처</button></div>
 <h3 class="section-label">연결된 시선 <span class="muted">${String(sources.length).padStart(2,'0')}</span></h3><div class="source-grid source-grid-three">${sources.map(src=>`<button class="source-card ${src.id===s.camera?'active':''}" data-action="camera" data-id="${src.id}" aria-pressed="${src.id===s.camera}"><div class="row">${ic(src.icon)}${src.id===s.camera?ic('check'):''}</div><strong>${src.name}</strong><small>${src.place} · ${stamp(src.duration)}</small><p class="source-summary">${src.summary}</p></button>`).join('')}</div>
 <div class="row"><h3 class="section-label">저장한 장면 ${records.length?`<span class="muted">${records.length}</span>`:''}</h3><button class="text-button" data-action="ai-capture">${ic('sparkle')}AI 장면 제안</button></div>${records.length?records.map(r=>`<button class="capture-card full" data-action="open-record" data-id="${esc(r.id)}"><img src="assets/${source.image}" alt="저장한 예시 장면"><span><strong>${esc(r.kind)} · ${timecode(r.playhead||0)}</strong><small>${esc(r.place)} · ${esc(r.time)}</small></span>${ic('chevron')}</button>`).join(''):'<div class="empty capture-empty">'+ic('bookmark')+'<span>필요한 순간을 캡처하거나 북마크하세요.</span></div>'}`;
}
export function deviceView(s,ic){return `<div class="row"><div class="eyebrow"><i class="dot"></i>나의 현장 장비</div><span class="tag subtle">${s.team==='현장 2팀'?'PG-028':'PG-041'}</span></div><h2 class="tool-heading">PARALLAX Glass</h2><p class="subcopy">${s.team==='현장 2팀'?'이서준 경사':'김도윤 경위'} · 폴더블과 연결된 나의 시야</p>
 <div class="glass-product"><img src="assets/parallax-glasses.png" alt="흰색 프레임과 푸른 렌즈의 PARALLAX AR 글래스"><button class="product-hotspot lens" data-action="device-feature" data-value="lens" aria-label="AR 렌즈 정보">${ic('plus')}</button><button class="product-hotspot camera" data-action="device-feature" data-value="camera" aria-label="전면 카메라 정보">${ic('plus')}</button><button class="product-hotspot control" data-action="device-feature" data-value="control" aria-label="측면 컨트롤 정보">${ic('plus')}</button><span class="product-caption">장비의 포인트를 눌러 확인하세요</span></div>
 <div class="device-metrics"><div><small>연결 상태</small><strong><i class="dot"></i>${s.connected?'연결됨':'연결 끊김'}</strong></div><div><small>배터리</small><strong>${s.team==='현장 2팀'?'82':'91'}<span>%</span></strong></div><div><small>기록</small><strong>${s.recording?'기록 중':'대기 중'}</strong></div></div>
 <button class="primary-button full" data-action="camera" data-id="ar" style="margin-top:18px">${ic('glasses')}내 AR 시야 열기 ${ic('arrow')}</button><div class="info-list"><div class="row"><span>저장 위치</span><span>이 기기 · 사건 자료</span></div><div class="row"><span>동기화</span><span>${s.online?'동기화됨':'전송 대기'}</span></div><div class="row"><span>대체 기록</span><span>폴더블 카메라</span></div></div><div class="button-row"><button class="secondary-button" data-action="connect">${s.connected?'연결 끊김 시험':'다시 연결'}</button><button class="secondary-button" data-action="record">${ic('video')}${s.recording?'기록 종료':'기록 시작'}</button></div><button class="text-button full" data-action="hardware" style="margin-top:12px">${ic('settings')}물리버튼 설정</button><p class="subcopy" style="margin-top:14px">장비 연결과 기록은 프로토타입 시뮬레이션입니다.</p>`;}
