import {createState,reduce} from './state.mjs';

const icons={
 map:'<path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Z"/><path d="M9 3v15m6-12v15"/>',
 mission:'<rect x="5" y="4" width="14" height="17" rx="3"/><path d="M9 4V2h6v2M9 10h6m-6 5h4"/>',
 video:'<rect x="3" y="5" width="13" height="14" rx="3"/><path d="m16 10 5-3v10l-5-3"/>',
 records:'<path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9l-6-6Z"/><path d="M14 3v6h6M8 13h8m-8 4h5"/>',
 messages:'<path d="M21 11a8 8 0 0 1-8 8H8l-5 3v-7a8 8 0 1 1 18-4Z"/><path d="M8 10h8m-8 4h5"/>',
 glasses:'<path d="M2 12h20M2 12l2-7h4m14 7-2-7h-4"/><rect x="2" y="12" width="8" height="7" rx="2"/><rect x="14" y="12" width="8" height="7" rx="2"/>',
 handoff:'<path d="M4 7h15l-4-4m5 14H5l4 4M19 7l-4 4M5 17l4-4"/>',
 mic:'<rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2m-7 9v3m-4 0h8"/>',
 arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',
 up:'<path d="M6 18 18 6M6 6h12v12"/>',
 chevron:'<path d="m9 5 7 7-7 7"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 close:'<path d="m6 6 12 12M6 18 18 6"/>',
 alert:'<path d="m10 3-8 15a2 2 0 0 0 2 3h16a2 2 0 0 0 2-3L14 3a2 2 0 0 0-4 0Z"/><path d="M12 8v5m0 4h.01"/>',
 bell:'<path d="M18 8a6 6 0 0 0-12 0c0 8-3 8-3 10h18c0-2-3-2-3-10M10 22h4"/>',
 pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',
 person:'<circle cx="12" cy="7" r="3"/><path d="M5 21v-2a7 7 0 0 1 14 0v2"/>',
 target:'<circle cx="12" cy="12" r="6"/><path d="M12 2v5m0 10v5M2 12h5m10 0h5"/>',
 layers:'<path d="m12 3 10 5-10 5L2 8l10-5ZM2 12l10 5 10-5M2 16l10 5 10-5"/>',
 camera:'<path d="m8 5 2-3h4l2 3h4a2 2 0 0 1 2 2v12H2V7a2 2 0 0 1 2-2h4Z"/><circle cx="12" cy="12" r="4"/>',
 drone:'<circle cx="5" cy="5" r="3"/><circle cx="19" cy="5" r="3"/><circle cx="5" cy="19" r="3"/><circle cx="19" cy="19" r="3"/><path d="m7 7 10 10M7 17 17 7"/>',
 play:'<path d="m8 4 12 8-12 8V4Z"/>',pause:'<path d="M8 5v14M16 5v14"/>',
 signal:'<path d="M4 19v-3m5 3v-7m5 7V8m5 11V3"/>',
 battery:'<rect x="2" y="7" width="18" height="10" rx="2"/><path d="M23 10v4M5 10h11v4H5Z"/>',
 fold:'<rect x="6" y="2" width="12" height="20" rx="3"/><path d="M10 18h4"/>',
 unfold:'<rect x="2" y="4" width="20" height="16" rx="3"/><path d="M12 4v16"/>',
 send:'<path d="m22 2-7 20-4-9-9-4L22 2ZM11 13l6-6"/>',
 sparkle:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3Z"/>',
 link:'<path d="m10 13 4-4m-6 7-2 2a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m2 1 2-2a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0"/>',
 settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',
 shield:'<path d="m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6l9-4Z"/><path d="m8 12 3 3 5-6"/>'
};
const ic=n=>`<svg class="icon" aria-hidden="true" viewBox="0 0 24 24">${icons[n]||icons.mission}</svg>`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles={mission:'현재 임무',map:'공간 작전',video:'영상 확인',records:'현장 기록',report:'보고서 작성',messages:'소통 · 보고',handoff:'인계 검토',device:'AR 글래스'};
const menu=[['mission','임무'],['map','지도'],['video','영상'],['records','기록'],['messages','소통']];
const sources=[{id:'cctv',name:'공동현관 CCTV',place:'1층 · 동측 출입구',icon:'camera',time:'12:14:32'},{id:'ar',name:'내 AR 글래스',place:'2층 · 계단실',icon:'glasses',time:'12:12:08'},{id:'body',name:'동료 바디캠',place:'1층 · 후면 출입구',icon:'video',time:'12:11:43'},{id:'drone',name:'현장 드론',place:'건물 외곽 · 상공',icon:'drone',time:'12:10:16'}];
let state=createState();
try{const saved=JSON.parse(localStorage.getItem('parallax-case-v1'));if(saved?.version===1)state={...state,...saved};else if(innerWidth<700)state.folded=true;}catch{if(innerWidth<700)state.folded=true;}
state.briefing=false;
let modalType=null,toastTimer,storageAvailable=true,previousFocus=null;
const app=document.querySelector('#app'),modalRoot=document.querySelector('#modal-root');
function persist(){try{localStorage.setItem('parallax-case-v1',JSON.stringify(state));}catch{storageAvailable=false;}}
function dispatch(action,redraw=true){state=reduce(state,action);persist();if(redraw)render();}
const now=()=>new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false});
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
function toast(message){clearTimeout(toastTimer);const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),3200);}
function nav(view,panel){dispatch({type:'NAV',view,panel:panel??(view==='map'?'primary':'secondary')});}
function navItem(view,label,active){return `<button class="nav-item ${active===view?'active':''}" data-action="nav" data-view="${view}" aria-label="${label}" ${active===view?'aria-current="page"':''}>${ic(view)}<span>${label}</span></button>`;}
function toolSelect(panel,view){return `<select aria-label="${panel==='primary'?'왼쪽':'오른쪽'} 작업 패널" data-panel-select="${panel}">${Object.entries(titles).map(([id,t])=>`<option value="${id}" ${id===view?'selected':''}>${t}</option>`).join('')}</select>`;}
function panel(view,side){return `<section class="pane ${view==='map'?'map-pane':''}" data-panel="${side}" aria-label="${side==='primary'?'왼쪽':'오른쪽'} ${titles[view]}">${view==='map'?mapView(side):`<div class="panel-toolbar"><h2>${ic(view)}${titles[view]}</h2>${toolSelect(side,view)}</div><div class="panel-content">${views[view]?.()||missionView()}</div>`}</section>`;}
function render(){
 document.documentElement.dataset.theme=state.theme;
 document.querySelector('meta[name="theme-color"]').content=state.theme==='light'?'#f3f5f2':'#0a1517';
 const current=state.folded?state.active:state.secondary;
 app.innerHTML=`<main class="preview ${state.folded?'compact':''}">
 <header class="studio-head"><div class="wordmark"><span class="brand-icon"><i></i><i></i><i></i></span>PARALLAX</div><div class="studio-meta"><span>현장의 맥락을, 다음 사람에게.</span><span class="prototype-pill">Interactive concept · 01</span></div><div class="studio-controls"><div class="theme-switch" aria-label="화면 테마"><button data-action="theme" data-value="light" class="${state.theme==='light'?'active':''}" aria-pressed="${state.theme==='light'}">화이트</button><button data-action="theme" data-value="dark" class="${state.theme==='dark'?'active':''}" aria-pressed="${state.theme==='dark'}">다크</button></div><div class="preview-controls" aria-label="기기 화면 크기"><button data-action="unfold" class="${!state.folded?'active':''}">${ic('unfold')}펼친 화면</button><button data-action="fold" class="${state.folded?'active':''}">${ic('fold')}접힌 화면</button></div></div></header>
 <div class="device"><div class="statusbar"><span>12:16</span><div class="status-right"><span>PS-LTE</span>${ic('signal')}${ic('battery')}82%</div></div>
 <header class="app-header"><div class="case-head"><div class="case-avatar">${ic('shield')}</div><div><h1>화곡동 흉기 의심 신고</h1><p>사건 #260914-0128 <span aria-hidden="true">&nbsp; · &nbsp;</span>${state.team} <span aria-hidden="true">&nbsp; · &nbsp;</span>12:04 접수</p></div></div><div class="header-actions"><div class="mode-switch" aria-label="업무 모드"><button data-action="mode" data-value="field" class="${state.mode==='field'?'active':''}" aria-pressed="${state.mode==='field'}">현장 수행</button><button data-action="mode" data-value="review" class="${state.mode==='review'?'active':''}" aria-pressed="${state.mode==='review'}">인계 검토</button></div><button class="icon-button ${!state.alertRead?'badge-dot':''}" data-action="alert" aria-label="긴급 알림">${ic('bell')}</button><button class="icon-button profile" data-action="profile" aria-label="근무 정보">${state.team==='현장 2팀'?'이':'김'}</button></div></header>
 <div class="workspace-presets"><span>작업 공간</span><button data-action="preset" data-value="mission">지도 + 임무</button><button data-action="preset" data-value="report">영상 + 보고서</button><button data-action="preset" data-value="handoff">지도 + 인계</button><span class="preset-tip">각 패널 상단에서 작업을 바꿀 수 있어요</span></div><div class="workspace"><nav class="rail" aria-label="주 메뉴">${menu.map(([v,t])=>navItem(v,t,current)).join('')}<div class="spacer"></div>${navItem('handoff','인계',current)}${navItem('device','글래스',current)}</nav><div class="panels">${state.folded?panel(state.active,'primary'):panel(state.primary,'primary')+panel(state.secondary,'secondary')}</div></div>
 <footer class="app-footer"><div class="footer-left"><button class="device-status" data-action="nav" data-view="device">${ic('glasses')}<i class="dot" style="${!state.connected?'background:#efb77b':''}"></i>${state.connected?'AR 연결됨':'AR 연결 끊김'} <span class="muted">82%</span></button><span>${storageAvailable?(state.online?'사건 자료 동기화됨 · 시뮬레이션':'오프라인 · 이 기기에 저장됨'):'저장 공간 사용 불가 · 현재 세션만 유지'}</span></div><button class="voice-button" data-action="voice">${ic('mic')}${state.mode==='review'?'음성 브리핑':'음성 명령 · 보고'}</button></footer>
 <nav class="bottom-nav" aria-label="하단 메뉴">${menu.map(([v,t])=>navItem(v,t,current)).join('')}</nav></div>
 <div class="preview-foot"><span>디자인 프로토타입 · 가상 사건 / 생성 지도 / 영상·AR·전송 시뮬레이션 <button class="reset-demo" data-action="reset-demo">예시 초기화</button></span><span>${state.folded?'한 손으로 확인하고, 바로 행동하기':'지도는 그대로. 필요한 작업을 나란히.'}</span></div></main>`;
}
function mapView(side){
 const floorInfo={'1F':['동측 출입구','현장 2팀 · 확인 완료'], '2F':['2층 서편 · 담당 구역','현장 2팀 · 확인 진행 중'],'3F':['3층 · 인계 대상 구역','선행 팀 기록 기준 · 미확인'],'RF':['옥상 진입로','선행 팀 기록 기준 · 미확인']};
 const info=floorInfo[state.floor];
 return `<div class="map-view"><img class="map-image" style="transform:scale(${state.zoom})" src="assets/${state.theme==='light'?'scene-map-light.png':'scene-map.png'}" alt="중앙 건물이 민트색으로 강조된 가상 주거 지역 입체 지도"><div class="map-shade"></div><div class="map-top"><div class="row"><div><div class="eyebrow"><i class="dot"></i>현장 공간 · 가상 지도</div><h2>화곡동, 현장 주변</h2></div>${toolSelect(side,'map')}</div><div class="map-stats"><span class="glass-chip">${ic('person')}현장 2팀 · 3명</span><button class="glass-chip" data-action="layers">${ic('layers')}팀 · CCTV · 구역</button></div></div>
 <div class="floor-controls" aria-label="층 선택">${['RF','3F','2F','1F'].map(f=>`<button data-action="floor" data-value="${f}" class="${state.floor===f?'active':''}" aria-pressed="${state.floor===f}">${f}</button>`).join('')}</div>
 <div class="map-target"></div><button class="map-pin selected" style="left:50%;top:43%" data-action="camera" data-id="cctv" aria-label="공동현관 CCTV 열기"><span class="pin-symbol">${ic('camera')}</span><small>공동현관 CCTV</small></button>
 <button class="map-pin person" style="left:30%;top:58%" data-action="team"><span class="pin-symbol">${ic('person')}</span><small>이서준 · 현장 2팀</small></button>
 <button class="map-pin" style="left:28%;top:32%" data-action="camera" data-id="drone"><span class="pin-symbol">${ic('drone')}</span><small>드론 01</small></button>
 <button class="map-pin urgent" style="left:71%;top:51%" data-action="alert"><span class="pin-symbol">${ic('alert')}</span><small>계단실 · 주의 보고</small></button>
 <div class="map-bottom"><div class="row"><div class="map-scale">20 m · 개념도</div><div class="map-tools"><button class="icon-button" data-action="zoom" data-delta="0.2" aria-label="지도 확대">${ic('plus')}</button><button class="icon-button" data-action="zoom" data-delta="-0.2" aria-label="지도 축소">${ic('minus')}</button><button class="icon-button" data-action="locate" aria-label="지도 위치 초기화">${ic('target')}</button></div></div><div class="location-card"><div class="row"><div><div class="eyebrow">선택한 구역 <span>· ${state.floor}</span></div><h3>${info[0]}</h3><p>${info[1]}</p></div><button class="location-action" data-action="nav" data-view="${state.mode==='review'?'handoff':'mission'}" aria-label="선택 구역 임무 열기">${ic('up')}</button></div><div class="map-legend"><span><i class="legend-square selected"></i>선택 구역</span><span><i class="legend-square"></i>확인 기록</span><span><i class="legend-square unknown"></i>미확인</span></div></div></div></div>`;
}
function missionView(){const tasks=state.team==='현장 2팀'?[['베란다 창 개방 여부','지휘통제실 · 12:05'],['계단실 시야 및 조명 상태','현장 2팀 · 12:12'],['동측 출입구 합류 위치','증원 1팀 · 12:14']]:[['3층 인계 구역 확인','인계 자료 · 선행 팀 미확인'],['옥상 진입로 상태 확인','인계 자료 · 선행 팀 미확인'],['현장팀과 동측 출입구 합류','지휘통제실 · 12:14']];return `<div class="row"><div class="eyebrow"><i class="dot"></i>나의 현장 업무</div><span class="tag danger">위험도 높음 · 지휘실</span></div><div class="mission-card" style="margin-top:16px"><div class="row"><span class="tag">${state.taskStatus}</span><span class="eyebrow" style="color:#c9debd">임무 02</span></div><h2>${state.team==='현장 2팀'?'2층 서편 확인 및<br>증원팀 합류':'3층 인계 구역 확인'}</h2><p>현장의 정보를 확인하고 다음 팀과 연결하세요.</p><div class="mission-meta"><div><small>담당 역할</small><strong>현장 확인</strong></div><div><small>합류 위치</small><strong>동측 출입구</strong></div><div><small>${state.team==='현장 2팀'?'증원 도착':'인계 상태'}</small><strong>${state.team==='현장 2팀'?'약 6분':'수락 완료'}</strong></div></div></div>
 <button class="alert-card" data-action="alert"><span class="alert-icon">${ic('alert')}</span><div><strong>${state.alertRead?'확인한 현장 주의 사항':'새로운 현장 주의 사항'}</strong><p>계단실 조명 어두움 · 박민수 경장 · 12:12</p></div>${ic('chevron')}</button><div class="row"><h3 class="section-label">우선 확인 대상</h3><small>${state.checks.filter(Boolean).length} / 3 완료</small></div>${tasks.map(([t,s],i)=>`<button class="check-item ${state.checks[i]?'done':''}" data-action="check" data-index="${i}" role="checkbox" aria-checked="${state.checks[i]}"><span class="check-box">${state.checks[i]?ic('check'):''}</span><span><strong>${t}</strong><small>${s}</small></span></button>`).join('')}
 <div class="assignment"><div class="avatar-stack"><span class="mini-avatar">이</span><span class="mini-avatar">박</span><span class="mini-avatar">최</span></div><span>${state.team}</span><span class="muted">· 함께 확인 중</span><button class="text-button" data-action="team" style="margin-left:auto">팀 보기</button></div><div class="button-row"><button class="secondary-button" data-action="hold-task">${state.taskStatus==='보류'?'임무 재개':'보류'}</button><button class="primary-button" data-action="complete" ${state.taskStatus==='완료'?'disabled':''}>${ic('check')}${state.taskStatus==='완료'?'임무 완료됨':'완료 보고'}</button></div><div class="mission-foot"><span>임무 변경 1건 · 12:14</span><button class="text-button" data-action="changes">변경 사항 확인 ${ic('chevron')}</button></div>`;}
function videoView(){const source=sources.find(s=>s.id===state.camera)||sources[0];return `<div class="row"><div class="eyebrow">현장을 다른 시선으로</div><span class="tag subtle">예시 영상</span></div><h2 class="tool-heading">${source.name}</h2><p class="subcopy">${source.place} · 촬영 ${source.time}</p><div class="video-frame"><img src="assets/${source.id==='drone'?'scene-map.png':'scene-camera.png'}" alt="${source.id==='drone'?'가상 건물 상공 장면':'생성 이미지로 표현한 공동현관 예시 장면'}" style="${source.id==='ar'?'object-position:20% 50%;transform:scale(1.2)':''}"><div class="video-overlay"><span class="tag subtle">${ic(source.icon)} ${source.id.toUpperCase()} · 샘플</span><span>${source.time}</span></div><div class="video-bottom"><button class="icon-button" data-action="play-sample" aria-label="샘플 영상 안내" style="height:29px;min-width:29px">${ic('play')}</button><div class="video-progress"><span></span></div><span>00:32 / 01:24</span></div></div><div class="button-row"><button class="secondary-button" data-action="show-location">${ic('pin')}지도에서 보기</button><button class="primary-button" data-action="capture">${ic('camera')}장면 캡처</button></div><h3 class="section-label">연결된 시선 <span class="muted">04</span></h3><div class="source-grid">${sources.map(s=>`<button class="source-card ${s.id===source.id?'active':''}" data-action="camera" data-id="${s.id}" aria-pressed="${s.id===source.id}"><div class="row">${ic(s.icon)}<span class="tag subtle" style="padding:3px 5px;font-size:8px">샘플</span></div><strong>${s.name}</strong><small>${s.place}</small></button>`).join('')}</div><div class="row"><h3 class="section-label">주요 장면</h3><button class="text-button" data-action="ai-capture">${ic('sparkle')} AI 장면 제안</button></div><div class="capture-card"><img src="assets/scene-camera.png" alt="공동현관 주요 장면"><div><strong>동측 출입구 · 합류 지점</strong><small>지휘실 북마크 · 12:09</small></div><button class="icon-button" data-action="bookmark" aria-label="북마크 상세" style="margin-left:auto;height:32px;min-width:32px">${ic('chevron')}</button></div>`;}
function recordsView(){return `<div class="eyebrow"><i class="dot"></i>현장의 맥락을 남기세요</div><h2 class="tool-heading">현장 기록</h2><div class="row"><p class="subcopy">${state.records.length}개 기록 · 사건에 연결됨</p><span class="tag ${state.recording?'danger':'subtle'}">${state.recording?'녹화 중 · 시뮬레이션':'기록 대기'}</span></div><div class="button-row"><button class="secondary-button" data-action="record">${ic('video')}${state.recording?'녹화 종료':'폰 AR 녹화'}</button><button class="secondary-button" data-action="voice">${ic('mic')}음성 기록</button></div><button class="text-button" data-action="hardware" style="margin-top:7px">물리버튼 설정 ${ic('chevron')}</button><h3 class="section-label">오늘의 타임라인</h3>${state.records.map(r=>`<div class="record-item"><span class="record-mark">${ic(r.kind.includes('음성')?'mic':'camera')}</span><div><strong>${esc(r.title)}</strong><small>${esc(r.kind)} · ${esc(r.place)}</small></div><span class="record-time">${esc(r.time)}</span></div>`).join('')}<div class="briefing-box"><div class="row"><strong style="font-size:13px">기록을 보고서로</strong>${ic('sparkle')}</div><p style="margin:10px 0 15px">현장 기록을 모아 초안을 만들고,<br>검토한 내용을 보고하세요.</p><button class="primary-button" data-action="draft">보고서 초안 만들기 ${ic('arrow')}</button></div>`;}
function reportView(){return `<div class="row"><span class="eyebrow">사건 #260914-0128</span><span class="tag subtle">검토용 초안</span></div><h2 class="tool-heading">현장 상황 보고</h2><p class="subcopy">기록을 근거로 내용을 확인하고 수정하세요.</p><label class="field-label" for="recipient-report">보고 대상</label><select class="form-select" id="recipient-report" data-recipient><option ${state.recipient==='지휘통제실'?'selected':''}>지휘통제실</option><option ${state.recipient==='증원 1팀'?'selected':''}>증원 1팀</option></select><div class="row"><label class="field-label" for="report-body">보고 내용</label><button class="text-button" data-action="draft-fill">${ic('sparkle')}기록으로 초안 채우기</button></div><textarea id="report-body" data-draft placeholder="현장 확인 내용을 작성하세요.">${esc(state.draft)}</textarea><div class="draft-hint"><span>${storageAvailable?'입력 내용은 이 기기에 자동 저장':'현재 세션에만 저장'}</span><span id="draft-length">${state.draft.length}자</span></div><h3 class="section-label">연결된 근거 기록</h3>${state.records.slice(0,3).map(r=>`<div class="info-list" style="margin:0"><div class="row"><span>${esc(r.kind)} · ${esc(r.time)}</span><span>${esc(r.title)}</span></div></div>`).join('')}<div class="button-row"><button class="secondary-button" data-action="save-draft">초안 저장</button><button class="primary-button" data-action="send-report">${ic('send')}검토 후 보고</button></div><p class="subcopy" style="margin-top:13px">초안 생성과 전송은 로컬 시뮬레이션입니다.</p>`;}
function messagesView(){const queued=state.messages.filter(m=>m.status==='queued');return `<div class="row"><h2 class="tool-heading">현장 소통</h2><span class="tag subtle">${state.online?'연결됨':'오프라인'}</span></div><p class="subcopy">지휘실과 증원팀에 현장을 전달합니다.</p><div class="segment">${['지휘통제실','증원 1팀'].map(t=>`<button data-action="recipient" data-value="${t}" class="${state.recipient===t?'active':''}">${t}</button>`).join('')}</div>${queued.length?`<div class="queue"><span>전송 대기 ${queued.length}건</span><button class="text-button" data-action="retry">다시 전송</button></div>`:''}${state.messages.filter(m=>m.from===state.recipient||m.to===state.recipient).map(m=>`<article class="message ${m.from==='나'?'mine':''}"><div class="row"><span>${esc(m.from)}${m.to?` → ${esc(m.to)}`:''}</span><span>${esc(m.time)}</span></div><p>${esc(m.body).replace(/\n/g,'<br>')}</p><div class="message-status">${{received:'수신됨',sent:'전송됨 · 시뮬레이션',queued:'전송 대기 · 이 기기에 저장'}[m.status]}</div></article>`).join('')}<form class="composer" id="message-form"><input class="text-input" name="message" aria-label="메시지 내용" placeholder="현장 상황을 입력하세요" required autocomplete="off"><button type="submit" aria-label="메시지 전송">${ic('send')}</button></form><div class="button-row"><button class="secondary-button" data-action="voice">${ic('mic')}음성 보고</button><button class="secondary-button" data-action="nav" data-view="report">${ic('records')}상황 보고서</button></div><div class="section-label">다음 인력에게 연결</div><button class="source-card full" data-action="handoff-send"><div class="row"><strong>증원 1팀에 인계 요청</strong>${ic('handoff')}</div><small>구역 · 현장 기록 · 주요 장면을 함께 전달</small></button><button class="text-button" data-action="network" style="margin-top:17px">${state.online?'오프라인 상태 시험':'네트워크 연결 복구'}</button>`;}
function handoffView(){const accepted=state.handoff==='accepted';return `<div class="row"><span class="eyebrow">하나의 사건, 이어지는 현장</span><span class="tag ${accepted?'':'amber'}">${{pending:'검토 대기',held:'보류됨',accepted:'인계 수락됨',requested:'요청 발신됨',queued:'발신 대기'}[state.handoff]}</span></div>${state.handoff==='queued'?'<div class="queue"><span>인계 요청 전송 대기</span><button class="text-button" data-action="retry">다시 전송</button></div>':''}<div class="handoff-card"><span class="tag danger">위험도 높음 · 지휘실</span><h2>화곡동 흉기 의심 신고</h2><div class="handoff-people"><span>현장 2팀</span>${ic('arrow')}<span>증원 1팀</span></div><div class="row"><div><small>후속 투입 이유</small><p style="font-size:12px;color:#e1eccf;margin-top:5px">3층 미확인 구역 · 추가 확인</p></div><div><small>현장 도착까지</small><div class="eta">6<small>분</small></div></div></div></div><div class="briefing-box"><button data-action="briefing"><span style="display:flex;gap:8px;align-items:center">${ic(state.briefing?'pause':'play')}${state.briefing?'브리핑 일시정지':'음성 브리핑 듣기'}</span><span class="muted">약 30초</span></button>${state.briefing?'<p style="margin-top:12px">2층 서편 확인 중. 계단실 조명 확인 필요. 증원팀은 동측 출입구에서 합류 예정입니다.</p>':''}</div><h3 class="section-label">지금 이어받을 내용</h3><p class="summary-line">선행 팀은 2층 서편을 확인 중입니다. <strong>3층과 옥상 진입로는 미확인</strong>이며, 계단실 조명에 대한 주의 보고가 있습니다.</p><div class="info-list" style="margin-top:0"><div class="row"><span>긴급 변경</span><button class="text-button" data-action="changes">합류 위치 변경 1건 →</button></div><div class="row"><span>사진 · 음성 기록</span><button class="text-button" data-action="nav" data-view="records">기록 ${state.records.length}개 보기 →</button></div><div class="row"><span>현장 자료</span><button class="text-button" data-action="nav" data-view="video">영상 4개 · 주요 장면 보기 →</button></div><div class="row"><span>지도 인사이트</span><button class="text-button" data-action="handoff-map">미확인 구역 확인 →</button></div></div>${accepted?`<div class="briefing-box"><p>인계 내용을 수락했습니다. AR 연결을 확인한 뒤 현장 업무를 이어가세요.</p></div><button class="primary-button full" data-action="continue" style="margin-top:17px">${ic('glasses')}AR로 이어받기</button>`:`<label class="handoff-check"><input type="checkbox" data-reviewed ${state.reviewed?'checked':''}>남은 임무와 변경 사항을 확인했습니다.</label><div class="button-row"><button class="secondary-button" data-action="hold-handoff">보류</button><button class="primary-button" data-action="accept" ${!state.reviewed?'disabled':''}>인계 수락 ${ic('arrow')}</button></div>`}<p class="subcopy" style="margin-top:14px">자료를 열람하는 것과 인계 수락은 별개입니다.</p>`;}
function deviceView(){return `<div class="eyebrow"><i class="dot"></i>현장의 시선을 연결합니다</div><h2 class="tool-heading">PARALLAX Glass</h2><p class="subcopy">${state.team==='현장 2팀'?'이서준 경사 · PG-028':'김도윤 경위 · PG-041'}</p><div class="device-illustration" aria-label="AR 글래스 개념 일러스트" role="img"><div class="glasses"><i></i></div></div><div class="row"><span class="tag ${state.connected?'':'amber'}">${state.connected?'연결됨 · 시뮬레이션':'연결 끊김'}</span><span class="tag subtle">${state.team==='현장 2팀'?'82':'91'}% 배터리</span></div><div class="info-list"><div class="row"><span>기록 상태</span><span>${state.recording?'녹화 중 · 샘플':'기록 대기'}</span></div><div class="row"><span>저장 위치</span><span>이 기기 · 사건 자료</span></div><div class="row"><span>동기화</span><span>${state.online?'완료 · 시뮬레이션':'전송 대기'}</span></div><div class="row"><span>대체 기록</span><span>폴더블 카메라</span></div></div><div class="button-row"><button class="secondary-button" data-action="connect">${state.connected?'연결 끊김 시험':'다시 연결'}</button><button class="primary-button" data-action="record">${ic('video')}${state.recording?'기록 종료':'기록 시작'}</button></div><button class="secondary-button full" data-action="hardware" style="margin-top:10px">${ic('settings')}물리버튼 설정</button><p class="subcopy" style="margin-top:18px">실제 AR 장비 연동 전의 인터랙션 프로토타입입니다.</p>`;}
const views={mission:missionView,video:videoView,records:recordsView,report:reportView,messages:messagesView,handoff:handoffView,device:deviceView};

function openModal(type,body){previousFocus=document.activeElement;modalType=type;modalRoot.innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="${type}" tabindex="-1"><button class="icon-button close" data-action="close" aria-label="닫기">${ic('close')}</button>${body}</section></div>`;app.inert=true;modalRoot.querySelector('.close').focus();}
function closeModal(){modalRoot.innerHTML='';modalType=null;app.inert=false;if(previousFocus?.isConnected)previousFocus.focus();else document.querySelector('.voice-button')?.focus();}
function alertModal(){openModal('현장 주의 사항',`<span class="tag amber">현장 경찰 보고</span><h2>계단실 조명이 어둡습니다.</h2><p>박민수 경장 · 현장 2팀<br>12:12 수신 · 2층 계단실</p><div class="briefing-box"><p>“2층 계단실 조명이 꺼져 있습니다. 이동 시 조명 상태를 확인해 주세요.”</p></div><div class="button-row"><button class="secondary-button" data-action="alert-map">지도 위치</button><button class="primary-button" data-action="alert-read">${ic('check')}내용 확인</button></div>`);}
function voiceModal(){if(state.mode==='review'){nav('handoff');toggleBriefing();return;}openModal('음성 명령 및 보고',`<span class="tag">음성 작업</span><h2>말로 남기는 현장.</h2><p>이 프로토타입은 마이크에 접근하지 않습니다.<br>예시 음성을 불러오거나 내용을 직접 입력하세요.</p><div class="waveform">${[12,24,19,42,55,30,60,41,26,48,22,35,14,27,12].map(h=>`<i style="height:${h}px"></i>`).join('')}</div><button class="secondary-button full" data-action="voice-example">예시 음성 불러오기</button><textarea id="voice-input" aria-label="음성 인식 내용" placeholder="예: 계단실 조명 확인 필요"></textarea><div class="button-row"><button class="secondary-button" data-action="voice-save">기록에 저장</button><button class="primary-button" data-action="voice-send">${ic('send')}보고하기</button></div><div class="button-row"><button class="text-button" data-action="voice-map">명령: 지도 열기</button><button class="text-button" data-action="voice-record">명령: 기록 시작</button></div>`);}
function toggleBriefing(){
 if(!('speechSynthesis' in window)){toast('이 브라우저는 음성 재생을 지원하지 않습니다. 브리핑 전사를 표시합니다.');dispatch({type:'BRIEFING'});return;}
 if(state.briefing){speechSynthesis.cancel();dispatch({type:'BRIEFING'});return;}
 dispatch({type:'BRIEFING'});const utterance=new SpeechSynthesisUtterance('화곡동 흉기 의심 신고 인계 브리핑입니다. 현장 2팀은 2층 서편을 확인 중입니다. 3층과 옥상 진입로는 미확인입니다. 계단실 조명이 어둡다는 현장 보고가 있습니다. 증원 1팀은 약 6분 후 동측 출입구에서 합류 예정입니다.');utterance.lang='ko-KR';utterance.rate=.96;utterance.onend=()=>{if(state.briefing)dispatch({type:'BRIEFING'});};utterance.onerror=()=>{if(state.briefing)dispatch({type:'BRIEFING'});toast('음성 재생이 지원되지 않습니다. 인계 요약을 확인해 주세요.');};speechSynthesis.speak(utterance);
}
function fillDraft(){return `사건: 화곡동 흉기 의심 신고 (#260914-0128)\n보고자: ${state.team}\n\n현장 기록 요약\n${state.records.map(r=>`• ${r.time} ${r.place} — ${r.title}`).join('\n')}\n\n후속 사항\n증원 1팀과 동측 출입구에서 합류 예정.\n3층 및 옥상 진입로는 선행 팀 기록 기준 미확인.\n\n[검토용 예시 초안 · 전송 전 사실관계 확인 필요]`;}
function addRecord(title,kind='장면 캡처'){dispatch({type:'ADD_RECORD',record:{id:uid(),title,kind,time:now(),place:state.floor+' · 현장'}});}
document.addEventListener('click',e=>{
 const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
 switch(a){
 case 'preset':{const target=b.dataset.value;dispatch({type:'NAV',panel:'primary',view:target==='report'?'video':'map'},false);dispatch({type:'NAV',panel:'secondary',view:target});break;}
 case 'theme':dispatch({type:'THEME',value:b.dataset.value});break;
 case 'fold':if(!state.folded)dispatch({type:'FOLD'});break;
 case 'unfold':if(state.folded)dispatch({type:'FOLD'});break;
 case 'nav':nav(b.dataset.view);break;
 case 'mode':dispatch({type:'MODE',value:b.dataset.value});break;
 case 'floor':dispatch({type:'FLOOR',value:b.dataset.value});break;
 case 'zoom':dispatch({type:'ZOOM',delta:Number(b.dataset.delta)});break;
 case 'locate':state={...state,zoom:1,floor:'2F'};persist();render();toast('담당 구역으로 돌아왔습니다.');break;
 case 'camera':dispatch({type:'CAMERA',id:b.dataset.id});break;
 case 'show-location':dispatch({type:'NAV',panel:'primary',view:'map'});if(!state.folded)state.active='video';toast('선택한 영상의 촬영 위치입니다.');break;
 case 'layers':openModal('지도 레이어',`<span class="tag">공간 작전</span><h2>지도에 표시된 정보</h2><div class="info-list"><div class="row"><span>현장 팀 위치</span><span>이서준 · 12:14 갱신</span></div><div class="row"><span>CCTV · 드론</span><span>클릭해 연결 자료 확인</span></div><div class="row"><span>선택한 구역</span><span>라임색 외곽 강조</span></div><div class="row"><span>미확인 구역</span><span>기록 기준 · 안전 여부 아님</span></div></div><p style="margin-top:18px">입체 지도는 생성 이미지이며 층 선택은 해당 층의 임무 정보를 표시합니다.</p>`);break;
 case 'team':openModal('현장 팀',`<span class="tag">현장 2팀</span><h2>같은 현장, 세 개의 시선.</h2><div class="info-list">${[['이서준 경사','2층 서편 · 현장 확인'],['박민수 경장','2층 계단실 · 현장 확인'],['최지훈 순경','1층 동측 · 합류 지원']].map(([n,r])=>`<div class="row"><span>${n}</span><span>${r}</span></div>`).join('')}</div><button class="primary-button full" data-action="team-chat" style="margin-top:22px">소통 화면 열기</button>`);break;
 case 'team-chat':closeModal();nav('messages');break;
 case 'alert':alertModal();break;
 case 'alert-read':dispatch({type:'ALERT_READ'});closeModal();toast('주의 사항을 확인했습니다.');break;
 case 'alert-map':closeModal();dispatch({type:'FLOOR',value:'2F'});nav('map','primary');break;
 case 'check':dispatch({type:'CHECK',index:Number(b.dataset.index)});break;
 case 'hold-task':dispatch({type:'HOLD_TASK'});toast(`임무가 ${state.taskStatus==='보류'?'보류되었습니다.':'재개되었습니다.'}`);break;
 case 'complete':if(!state.checks.every(Boolean)){toast('우선 확인 대상 3개를 확인한 뒤 완료할 수 있습니다.');break;}dispatch({type:'COMPLETE'});addRecord('담당 임무 확인 완료','임무 보고');toast('임무 완료가 기록되었습니다.');break;
 case 'changes':openModal('임무 변경 사항',`<span class="tag amber">새로운 변경 1건</span><h2>합류 위치가 변경되었습니다.</h2><p>지휘통제실 · 12:14</p><div class="info-list"><div class="row"><span>이전</span><span>정문 앞</span></div><div class="row"><span>현재</span><span>동측 출입구</span></div></div><p style="margin-top:17px">증원 1팀이 이동 중입니다. 변경된 위치는 현재 임무와 인계 자료에 함께 반영됩니다.</p><button class="primary-button full" data-action="close" style="margin-top:20px">내용 확인</button>`);break;
 case 'capture':addRecord(`${sources.find(s=>s.id===state.camera).name} · 장면 캡처`);toast('촬영 위치와 시각을 포함해 기록에 저장했습니다.');break;
 case 'ai-capture':openModal('AI 주요 장면 제안',`<span class="tag">AI 제안 · 시뮬레이션</span><h2>합류 지점이 보이는 장면</h2><p>예시 자료의 동측 출입구 장면입니다. 원본을 확인하고 기록에 추가하세요.</p><div class="video-frame"><img src="assets/scene-camera.png" alt="예시 출입구 장면"></div><button class="primary-button full" data-action="ai-save">검토한 장면 저장</button>`);break;
 case 'ai-save':addRecord('동측 출입구 · AI 제안 확인','장면 캡처');closeModal();toast('검토한 장면을 저장했습니다.');break;
 case 'bookmark':openModal('주요 장면',`<span class="tag">지휘실 북마크</span><h2>동측 출입구 · 합류 지점</h2><p>공동현관 CCTV · 12:09 · 1층 동측<br>인계 자료에 포함된 장면입니다.</p><div class="video-frame"><img src="assets/scene-camera.png" alt="북마크된 예시 장면"></div><button class="primary-button full" data-action="bookmark-map">지도에서 확인</button>`);break;
 case 'bookmark-map':closeModal();dispatch({type:'FLOOR',value:'1F'});nav('map','primary');break;
 case 'play-sample':toast('생성 이미지 기반의 영상 화면 예시입니다. 실제 스트리밍은 연결되지 않았습니다.');break;
 case 'record':dispatch({type:'RECORD'});if(!state.recording)addRecord('폰 AR 녹화 세션 종료','촬영 시뮬레이션');toast(state.recording?'샘플 녹화 상태를 시작했습니다.':'샘플 녹화 기록을 저장했습니다.');break;
 case 'hardware':openModal('물리버튼 설정',`<span class="tag subtle">기기 설정 제안</span><h2>화면을 보지 않고 기록하기</h2><div class="info-list"><div class="row"><span>한 번 누르기</span><span>주요 장면 캡처</span></div><div class="row"><span>길게 누르기</span><span>음성 기록</span></div><div class="row"><span>두 번 누르기</span><span>녹화 시작 · 종료</span></div></div><p style="margin-top:20px">실제 물리버튼 연결은 네이티브 앱에서 구현할 기능입니다.</p>`);break;
 case 'draft':if(!state.draft)dispatch({type:'DRAFT',value:fillDraft()},false);nav('report');break;
 case 'draft-fill':if(state.draft.trim()){openModal('초안 다시 생성',`<h2>현재 초안을 바꿀까요?</h2><p>편집한 내용을 현재 기록으로 생성한 예시 초안으로 교체합니다.</p><div class="button-row"><button class="secondary-button" data-action="close">유지하기</button><button class="primary-button" data-action="replace-draft">교체하기</button></div>`);}else{dispatch({type:'DRAFT',value:fillDraft()});toast('현재 기록을 바탕으로 예시 초안을 만들었습니다.');}break;
 case 'replace-draft':dispatch({type:'DRAFT',value:fillDraft()});closeModal();break;
 case 'save-draft':persist();toast(storageAvailable?'초안을 이 기기에 저장했습니다.':'저장 공간을 사용할 수 없어 현재 세션에만 유지됩니다.');break;
 case 'send-report':if(!state.draft.trim()){toast('보고 내용을 먼저 작성해 주세요.');break;}openModal('보고 내용 최종 확인',`<span class="tag">${esc(state.recipient)}</span><h2>이 내용으로 보고합니다.</h2><p style="white-space:pre-wrap;max-height:280px;overflow:auto">${esc(state.draft)}</p><div class="button-row"><button class="secondary-button" data-action="close">계속 수정</button><button class="primary-button" data-action="confirm-report">${state.online?'보고 전송':'오프라인 대기열에 저장'}</button></div>`);break;
 case 'confirm-report':dispatch({type:'SEND_REPORT',id:uid(),time:now(),recipient:state.recipient});closeModal();nav('messages');toast(state.online?'보고를 전송했습니다. (시뮬레이션)':'보고를 저장했습니다. 연결 후 다시 전송하세요.');break;
 case 'recipient':dispatch({type:'RECIPIENT',value:b.dataset.value});break;
 case 'retry':if(!state.online){toast('오프라인입니다. 연결 복구 후 다시 전송할 수 있습니다.');break;}dispatch({type:'RETRY'});toast('대기 중인 보고를 전송했습니다. (시뮬레이션)');break;
 case 'network':dispatch({type:'ONLINE',value:!state.online});toast(state.online?'연결이 복구되었습니다. 대기 중인 보고를 다시 전송하세요.':'오프라인 상태로 전환했습니다.');break;
 case 'handoff-send':openModal('인계 작성',`<span class="tag">받는 팀 · 증원 1팀</span><h2>현장을 다음 사람에게.</h2><p>사건 #260914-0128<br>현재 임무, 확인 구역, 기록 ${state.records.length}개, 영상 북마크를 전달합니다.</p><label class="field-label" for="handoff-note">추가 전달 사항</label><textarea id="handoff-note" placeholder="후속 팀에 남길 내용을 입력하세요"></textarea><button class="primary-button full" data-action="confirm-handoff" style="margin-top:18px">인계 요청 보내기</button>`);break;
 case 'confirm-handoff':{const note=document.querySelector('#handoff-note').value.trim();if(note)addRecord(note,'인계 메모');dispatch({type:'REQUEST_HANDOFF'});closeModal();nav('handoff');toast(state.online?'인계를 요청했습니다. 수락 대기 중입니다.':'인계 요청을 이 기기에 저장했습니다.');break;}
 case 'handoff-map':dispatch({type:'FLOOR',value:'3F'});nav('map','primary');break;
 case 'hold-handoff':dispatch({type:'HOLD_HANDOFF'});toast('인계를 보류했습니다. 선행 팀 담당 상태는 유지됩니다.');break;
 case 'accept':if(state.reviewed)openModal('인계 수락 확인',`<span class="tag">현장 2팀 → 증원 1팀</span><h2>현장 업무를 이어받습니다.</h2><p>3층·옥상 진입로 확인, 동측 출입구 합류 및 현장 자료를 인수합니다.</p><div class="button-row"><button class="secondary-button" data-action="close">검토로 돌아가기</button><button class="primary-button" data-action="confirm-accept">수락 확정</button></div>`);break;
 case 'confirm-accept':dispatch({type:'ACCEPT'});closeModal();toast('인계를 수락했습니다. AR로 이어받기를 눌러 시작하세요.');break;
 case 'continue':if(!state.connected){toast('AR 연결을 먼저 확인해 주세요.');nav('device');break;}dispatch({type:'CONTINUE'});toast('증원 1팀의 현장 임무를 시작합니다.');break;
 case 'connect':dispatch({type:'CONNECT'});toast(state.connected?'AR 연결을 복구했습니다. (시뮬레이션)':'AR 연결 끊김 상태입니다. 폰으로 기록할 수 있습니다.');break;
 case 'voice':voiceModal();break;
 case 'briefing':toggleBriefing();break;
 case 'voice-example':document.querySelector('#voice-input').value='2층 계단실 조명이 어둡습니다. 증원팀은 동측 출입구에서 합류 바랍니다.';break;
 case 'voice-save':case 'voice-send':{const text=document.querySelector('#voice-input').value.trim();if(!text){toast('기록할 내용을 입력하거나 예시 음성을 불러오세요.');break;}if(a==='voice-save'){addRecord(text,'음성 기록');closeModal();toast('음성 내용을 기록에 저장했습니다.');}else{dispatch({type:'DRAFT',value:text},false);closeModal();nav('report');toast('인식 내용을 확인한 뒤 보고하세요.');}break;}
 case 'voice-map':closeModal();nav('map','primary');break;
 case 'voice-record':closeModal();if(!state.recording)dispatch({type:'RECORD'});nav('records');toast('샘플 녹화 상태를 시작했습니다.');break;
 case 'reset-demo':openModal('예시 데이터 초기화',`<h2>처음 상태로 돌아갈까요?</h2><p>이 프로토타입에서 작성한 보고서와 메시지, 기록을 지우고 최초 예시 상태로 돌아갑니다.</p><div class="button-row"><button class="secondary-button" data-action="close">유지하기</button><button class="primary-button" data-action="confirm-reset">초기화</button></div>`);break;
 case 'confirm-reset':if('speechSynthesis' in window)speechSynthesis.cancel();state={...createState(),folded:state.folded,theme:state.theme};persist();closeModal();render();toast('처음 예시 상태로 돌아왔습니다.');break;
 case 'profile':openModal('근무 정보',`<span class="tag">근무 중</span><h2>${state.team==='현장 2팀'?'이서준 경사':'김도윤 경위'}</h2><p>화곡지구대 · ${state.team}<br>현재 사건: #260914-0128<br>가상의 사용자 및 사건 정보입니다.</p>`);break;
 case 'close':closeModal();break;
 }
});
document.addEventListener('change',e=>{if(e.target.matches('[data-panel-select]'))nav(e.target.value,e.target.dataset.panelSelect);if(e.target.matches('[data-recipient]'))dispatch({type:'RECIPIENT',value:e.target.value},false);if(e.target.matches('[data-reviewed]'))dispatch({type:'REVIEWED',value:e.target.checked});});
document.addEventListener('input',e=>{if(e.target.matches('[data-draft]')){dispatch({type:'DRAFT',value:e.target.value},false);document.querySelector('#draft-length').textContent=state.draft.length+'자';}});
document.addEventListener('submit',e=>{if(e.target.id==='message-form'){e.preventDefault();const data=new FormData(e.target);dispatch({type:'MESSAGE',body:String(data.get('message')||''),id:uid(),time:now()});toast(state.online?'메시지를 전송했습니다. (시뮬레이션)':'메시지가 전송 대기열에 저장되었습니다.');}});
document.addEventListener('keydown',e=>{if(!modalType)return;if(e.key==='Escape'){closeModal();return;}if(e.key==='Tab'){const focusable=[...modalRoot.querySelectorAll('button:not(:disabled), input, textarea, select')];const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}});
render();
