import {zoneSummary} from './map-model.mjs';
import {situationEvents,selectedHistory} from './situation.mjs?v=situation4';
import {zones,selectedZoneKey,zoneRequests} from './zones.mjs';
import {sourceById} from './media.mjs?v=ops1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function zoneWork(s){
 const list=zoneRequests(s),remaining=list.filter(r=>s.zoneResults?.[r.id]?.status!=='완료').length;
 const name=zones.find(z=>z.id===selectedZoneKey(s)).name;
 return `<span class="tag subtle">사건 #260914-0128 · 가상 현장</span><h2>${esc(name)}</h2><p>담당 ${esc(zoneSummary(s,selectedZoneKey(s)).owner)} · 출처: 선행 팀 기록<br>자료 확인과 현장 업무 완료를 구분합니다.</p><div class="zone-counts"><span><strong>${remaining}</strong> 남은 업무</span><span><strong>${list.length-remaining}</strong> 완료</span><span><strong>${new Set(list.map(r=>r.source)).size}</strong> 연결 영상</span></div>${[...list].sort((a,b)=>(s.zoneResults?.[a.id]?.status==='완료')-(s.zoneResults?.[b.id]?.status==='완료')).map(r=>{const result=s.zoneResults?.[r.id];return `<article class="ops-row"><span class="tag ${result?.status==='완료'?'ops-done':'amber'}">${esc(result?.status||'재확인 필요')}</span><h3>${esc(r.title)}</h3><p>${esc(r.next)}</p><p class="ops-meta">미확인 사유 · ${esc(r.reason)}<br>출처 · ${esc(r.author)}</p>${result?`<p>최근 결과 · ${esc(result.body)}</p><small>${esc(result.time)} · ${esc(result.author)}</small>`:''}<p class="zone-evidence">${esc(sourceById(r.source).name)} · 총 ${Math.floor(sourceById(r.source).duration/60)}:${String(sourceById(r.source).duration%60).padStart(2,'0')}<br>${esc(sourceById(r.source).summary)}</p><div class="button-row"><button class="secondary-button" data-action="request-scene" data-id="${r.id}">${Math.floor(r.second/60)}:${String(r.second%60).padStart(2,'0')} 근거 영상</button><button class="primary-button" data-action="zone-result" data-id="${r.id}">확인 결과 남기기</button></div></article>`}).join('')||'<p>연결된 확인 요청이 없습니다. 새 요청을 작성해 인계할 수 있습니다.</p>'}<div class="button-row"><button class="secondary-button" data-action="zone-request-write">이 구역에 요청 추가</button><button class="secondary-button" data-action="ops-history">변경 이력</button></div>`;
}
export function resultForm(s,id){const r=s.handoffRequests.find(r=>r.id===id),d=s.resultDrafts?.[id]??s.zoneResults?.[id]?.body??'';if(!r)return '';return `<h2>${esc(r.title)}</h2><p>확인한 내용과 남은 부분을 적어 주세요. 결과는 이 기기의 인계 자료와 기록에 연결됩니다.</p><label class="field-label">확인 결과<textarea data-result-draft="${esc(id)}" placeholder="확인한 범위와 관찰 내용을 입력하세요">${esc(d)}</textarea></label><label class="field-label">업무 상태<select class="form-select" id="result-status">${['재확인 필요','확인 중','완료'].map(v=>`<option ${v===(s.zoneResults?.[id]?.status||'재확인 필요')?'selected':''}>${v}</option>`).join('')}</select></label><button class="primary-button full" data-action="zone-result-save" data-id="${esc(id)}">결과 저장</button>`;}
export function historyView(s){const events=situationEvents(s),selected=selectedHistory(s);return `<h2>주요 변경 이력</h2><p>시연 이력과 이 기기에서 작성한 기록입니다. 항목을 선택해 연결된 근거를 확인하세요. 현재 임무·완료 상태는 유지됩니다.</p><div class="history-list">${events.map(c=>`<button class="history-item ${c.id===selected?.id?'selected':''}" data-action="history-select" data-id="${esc(c.id)}" aria-pressed="${c.id===selected?.id}"><span>${esc(c.time)}</span><strong>${esc(c.title)}</strong><small>${esc(c.who)} · ${s.changesRead?.[c.id]?'읽음':'미확인'}</small></button>`).join('')}</div>${selected?`<article class="ops-row"><span class="tag amber">${esc(selected.time)} 기록 검토 중</span><h3>${esc(selected.title)}</h3><p>${esc(selected.detail)}</p><p class="ops-meta">${esc(selected.who)} · ${esc(selected.time)}<br>사유 · ${esc(selected.why)}</p>${selected.next?`<p>다음 행동 · ${esc(selected.next)}</p>`:''}<div class="button-row">${selected.source?`<button class="secondary-button" data-action="history-scene" data-id="${esc(selected.id)}">${Math.floor(selected.second/60)}:${String(selected.second%60).padStart(2,'0')} 연결 장면</button>`:''}${selected.zone?`<button class="secondary-button" data-action="history-zone" data-id="${esc(selected.id)}">관련 구역 지도</button>`:''}<button class="secondary-button" data-action="change-read" data-id="${esc(selected.id)}" aria-pressed="${!!s.changesRead?.[selected.id]}">${s.changesRead?.[selected.id]?'기록 확인됨':'기록 확인'}</button></div></article><button class="primary-button full" data-action="history-exit">기록 검토 종료</button>`:'<p class="ops-meta">이력의 읽음 표시와 인계 요청 확인, 현장 업무 완료는 각각 구분됩니다.</p>'}`;}
export function historyBanner(s){const e=selectedHistory(s);return e?`<aside class="history-banner" aria-label="과거 기록 검토"><div><strong>${esc(e.time)} 기록 검토 중</strong><span>${esc(e.title)} · 현재 임무 상태 유지</span></div><button data-action="ops-history">이력 열기</button><button data-action="history-exit">검토 종료</button></aside>`:'';}
export function cameraDetails(){return `<span class="tag subtle">위치 미확정</span><h2>CCTV 연결 자료</h2><p>영상은 확인할 수 있지만, 이 카메라의 실제 설치 위치와 촬영 방향은 확인되지 않았습니다.</p><p>지도 표식은 시연용 가상 배치이며 실제 설치 위치나 감시 범위를 뜻하지 않습니다.</p><button class="primary-button full" data-action="camera" data-id="cctv">연결 영상 보기</button>`;}
export function resultSummary(s){const entries=Object.entries(s.zoneResults||{});return `<section class="ops-row"><div class="row"><h3>현장에서 이어서 확인한 결과</h3><button class="text-button" data-action="ops-history">지휘 변경 이력</button></div>${entries.length?entries.map(([id,r])=>`<p><strong>${esc(s.handoffRequests.find(v=>v.id===id)?.title||id)} · ${esc(r.status)}</strong><br>${esc(r.body)}<br><small>${esc(r.author)} · ${esc(r.time)}</small></p>`).join(''):'<p class="ops-meta">아직 작성된 현장 결과가 없습니다. 지도에서 구역을 선택해 남길 수 있습니다.</p>'}</section>`;}
